title: "EASYPEASY"
description: "THM ROOM"
author: yourname
#theme: jekyll-theme-minimal
remote_theme: pages-themes/Midnight

# Optional extras
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
